---
- name: Database Setup
  hosts: database
  become: true

  tasks:
    - name: Install mysql-server
      apt:
        name: mysql-server
        state: present
        update_cache: yes

    - name: Verify that MySQL server is up and running
      service:
        name: mysql
        state: started
        enabled: yes
