---
- name: Set Fact Test
  hosts: localhost
  become: true
  connection: local
  gather_facts: false
  vars:
    hostname: https://finance.dev.desjardins.com
    nodelist_in:
      - node: node 1
        ip: 10.22.22.22
      - node: node 2
        ip: 10.22.33.22
    NodeList: []

  tasks:
  
  - name: Set nodes1
    set_fact:
       NodeList: "{{ NodeList  + [ { 'noder': item.node , 'iper': item.ip} ] }}" 
    with_items: "{{ nodelist_in }}"  
   
  - name: Set nodes2
    set_fact:
       NodeList: "{{ NodeList }} + {{ [ { 'noder': item.node.split(' ')[0] | upper , 'iper': item.ip} ] }} " 
    with_items: "{{ nodelist_in }}" 

  - name: Set nodes3
    set_fact:
       NodeList: "{{ NodeList }} + {{ [ { 'noder': [{ 'nodelevel2': 'level 2' | upper}] , 'iper': item.ip} ] }} " 
    with_items: "{{ nodelist_in }}" 
  

#  - name: Set nodes4
#    set_fact:
#     NodeTest: >
#        {% for nodet in nodelist_in -%} 
#        { "{{NodeList }}","{{ { 'noder': nodet.node.split(' ')[0] | lower , 'iper': 'nodes4'} }}" }
#        {% endfor %}

  - name: Set nodes5
    set_fact:
      NodeList: >
       {%- for nodet in nodelist_in -%}
         {%- do NodeList.append({ 'noder': nodet.node.split(' ')[0] | upper , 'iper': 'nodes4'}) -%}
       {%- endfor -%}
       {{ NodeList }} 

  - name: Create a list with set fact
    set_fact:
      ltm: 
        vsname: "{{hostname.split('//')[1].split('.')[0] | upper }}_{{hostname.split('//')[1].split('.')[1] | upper }}_{{hostname | urlsplit('scheme')}}_virtual"  # FINANCING_DEV_https_virtual
        nodes: "{{ NodeList }}"

  - name: Debug LTM LIST
    debug:
      var: ltm

  - name: Debug message
    debug:
      msg: "{{ltm.nodes[0].noder}}"

  - name: Debug Node Test
    debug:
      var: NodeTest




  

