---
- name: Bring down loadbalancer
  hosts: loadbalancer
  become: true
  tasks:
    - name: Stop nginx
      service:
        name: nginx
        state: stopped

- name: Bring down web server
  hosts: webserver
  become: true
  tasks:
    - name: Stop apache2
      service:
        name: apache2
        state: stopped

- name: Restart database
  hosts: database
  become: true
  tasks:
    - name: Restart mysql
      service:
        name: mysql
        state: restarted

- name: Bring up web server
  hosts: webserver
  become: true
  tasks:
    - name: Start apache2
      service: 
        name: apache2
        state: started

- name: Bring up loadbalancer
  hosts: loadbalancer
  become: true
  tasks:
    - name: Start loadbalancer
      service:
        name: nginx
        state: started 
       


