---
- name: Web Server Setup
  hosts: webserver
  become: true
  gather_facts: false

  pre_tasks:

    - name: Include vars of stuff.yaml into the 'stuff' variable (2.2).
      include_vars:
        file: data.yml
      

  roles: 
    - apache2
    - demo_app

###################### Made change ###


