---
- name: Web Server Setup
  hosts: webserver
  become: true
 
  tasks:
    - name: Install Web Server Components
      apt:
        name: "{{item}}"
        state: present
        update_cache: yes
      with_items:
        - apache2
        - libapache2-mod-wsgi
        - python-pip
        - python-virtualenv
